function showAlert() {
    var myText = "atomic_number: 1"
    alert(myText);
}

// let flag = true;

// function displayInfo(element) {
//     let msg = "";
//     info.forEach(e => {
//         if (e.atomic_number === id) {
//             msg = "Atomic Number: " + e.atomic_number +
//                 "\nName: " + e.element_name +
//                 "\nElectrons: " + e.electrons +
//                 "\nProtons: " + e.protons +
//                 "\nAtomic Weight" + e.atomic_weight +
//                 "\nElectronic Configuration: " + e.electronic_configuration;
//         }
//     });
//     alert(msg);
// }

// const elementInfo = [{
//         "atomic_number": "1",
//         "element_name": "Hydrogen",
//         "element_symbol": "H",
//         "electrons": "1",
//         "protons": "1",
//         "neutrons": "0",
//         "atomic_weight": "1.00784u",
//         "electronic_configuration": "K1-L0-M0-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "2",
//         "element_name": "Helium",
//         "element_symbol": "He",
//         "electrons": "2",
//         "protons": "2",
//         "neutrons": "2",
//         "atomic_weight": "4.0026u",
//         "electronic_configuration": "K2-L0-M0-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "3",
//         "element_name": "Lithium",
//         "element_symbol": "Li",
//         "electrons": "3",
//         "protons": "3",
//         "neutrons": "4",
//         "atomic_weight": "6.941u",
//         "electronic_configuration": "K2-L1-M0-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "4",
//         "element_name": "Beryllium",
//         "element_symbol": "Be",
//         "electrons": "4",
//         "protons": "4",
//         "neutrons": "5",
//         "atomic_weight": "9.0121u",
//         "electronic_configuration": "K2-L2-M0-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "5",
//         "element_name": "Boron",
//         "element_symbol": "B",
//         "electrons": "5",
//         "protons": "5",
//         "neutrons": "6",
//         "atomic_weight": "10.811u",
//         "electronic_configuration": "K2-L3-M0-N0-O0-P0-Q0-R0",

//     },
//     {
//         "atomic_number": "6",
//         "element_name": "Carbon",
//         "element_symbol": "C",
//         "electrons": "6",
//         "protons": "6",
//         "neutrons": "6",
//         "atomic_weight": "12.0107u",
//         "electronic_configuration": "K2-L4-M0-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "7",
//         "element_name": "Nitrogen",
//         "element_symbol": "N",
//         "electrons": "7",
//         "protons": "7",
//         "neutrons": "7",
//         "atomic_weight": "14.0067u",
//         "electronic_configuration": "K2-L5-M0-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "8",
//         "element_name": "Oxygen",
//         "element_symbol": "O",
//         "electrons": "8",
//         "protons": "8",
//         "neutrons": "8",
//         "atomic_weight": "15.9994u",
//         "electronic_configuration": "K2-L6-M0-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "9",
//         "element_name": "Fluorine",
//         "element_symbol": "F",
//         "electrons": "9",
//         "protons": "9",
//         "neutrons": "10",
//         "atomic_weight": "18.998u",
//         "electronic_configuration": "K2-L7-M0-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "10",
//         "element_name": "Neon",
//         "element_symbol": "Ne",
//         "electrons": "10",
//         "protons": "10",
//         "neutrons": "10",
//         "atomic_weight": "18.99u",
//         "electronic_configuration": "K2-L8-M0-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "11",
//         "element_name": "Sodium",
//         "element_symbol": "Na",
//         "electrons": "11",
//         "protons": "11",
//         "neutrons": "12",
//         "atomic_weight": "22.98u",
//         "electronic_configuration": "K2-L8-M1-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "12",
//         "element_name": "Magnesium",
//         "element_symbol": "Mg",
//         "electrons": "12",
//         "protons": "12",
//         "neutrons": "12",
//         "atomic_weight": "24.30u",
//         "electronic_configuration": "K2-L8-M2-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "13",
//         "element_name": "Aluminium",
//         "element_symbol": "Al",
//         "electrons": "13",
//         "protons": "13",
//         "neutrons": "14",
//         "atomic_weight": "26.98u",
//         "electronic_configuration": "K2-L8-M3-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "14",
//         "element_name": "Silicon",
//         "element_symbol": "Si",
//         "electrons": "14",
//         "protons": "14",
//         "neutrons": "14",
//         "atomic_weight": "28.08u",
//         "electronic_configuration": "K2-L8-M4-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "15",
//         "element_name": "Phosphorus",
//         "element_symbol": "P",
//         "electrons": "15",
//         "protons": "15",
//         "neutrons": "16",
//         "atomic_weight": "30.97u",
//         "electronic_configuration": "K2-L8-M5-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "16",
//         "element_name": "Sulphur",
//         "element_symbol": "S",
//         "electrons": "16",
//         "protons": "16",
//         "neutrons": "16",
//         "atomic_weight": "32.06u",
//         "electronic_configuration": "K2-L8-M6-N0-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "17",
//         "element_name": "Chlorine",
//         "element_symbol": "Cl",
//         "electrons": "17",
//         "protons": "17",
//         "neutrons": "18",
//         "atomic_weight": "35.45u",
//         "electronic_configuration": "K2-L8-M7-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "18",
//         "element_name": "Argon",
//         "element_symbol": "Ar",
//         "electrons": "18",
//         "protons": "18",
//         "neutrons": "22",
//         "atomic_weight": "39.94u",
//         "electronic_configuration": "K2-L8-M8-N0-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "19",
//         "element_name": "Pottasium",
//         "element_symbol": "K",
//         "electrons": "19",
//         "protons": "19",
//         "neutrons": "20",
//         "atomic_weight": "39.09u",
//         "electronic_configuration": "K2-L8-M8-N1-O0-P0-Q0-R0",

//     },
//     {
//         "atomic_number": "20",
//         "element_name": "Calcium",
//         "element_symbol": "Ca",
//         "electrons": "20",
//         "protons": "20",
//         "neutrons": "20",
//         "atomic_weight": "40.07u",
//         "electronic_configuration": "K2-L8-M8-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "21",
//         "element_name": "Scandium",
//         "element_symbol": "Sc",
//         "electrons": "21",
//         "protons": "21",
//         "neutrons": "24",
//         "atomic_weight": "44.95u",
//         "electronic_configuration": "K2-L8-M9-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "22",
//         "element_name": "Titanium",
//         "element_symbol": "Ti",
//         "electrons": "22",
//         "protons": "22",
//         "neutrons": "26",
//         "atomic_weight": "47.86u",
//         "electronic_configuration": "K2-L8-M10-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "23",
//         "element_name": "Vanadium",
//         "element_symbol": "V",
//         "electrons": "23",
//         "protons": "23",
//         "neutrons": "28",
//         "atomic_weight": "50.94u",
//         "electronic_configuration": "K2-L8-M11-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "24",
//         "element_name": "Chromium",
//         "element_symbol": "Cr",
//         "electrons": "24",
//         "protons": "24",
//         "neutrons": "28",
//         "atomic_weight": "51.99u",
//         "electronic_configuration": "K2-L8-M13-N1-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "25",
//         "element_name": "Manganese",
//         "element_symbol": "Mn",
//         "electrons": "25",
//         "protons": "25",
//         "neutrons": "30",
//         "atomic_weight": "54.93u",
//         "electronic_configuration": "K2-L8-M13-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "26",
//         "element_name": "Iron",
//         "element_symbol": "Fe",
//         "electrons": "26",
//         "protons": "26",
//         "neutrons": "30",
//         "atomic_weight": "55.84u",
//         "electronic_configuration": "K2-L8-M14-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "27",
//         "element_name": "Cobalt",
//         "element_symbol": "Co",
//         "electrons": "27",
//         "protons": "27",
//         "neutrons": "32",
//         "atomic_weight": "58.93u",
//         "electronic_configuration": "K2-L8-M15-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "28",
//         "element_name": "Nickel",
//         "element_symbol": "Ni",
//         "electrons": "28",
//         "protons": "28",
//         "neutrons": "31",
//         "atomic_weight": "58.69u",
//         "electronic_configuration": "K2-L8-M16-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "29",
//         "element_name": "Copper",
//         "element_symbol": "Cu",
//         "electrons": "29",
//         "protons": "29",
//         "neutrons": "35",
//         "atomic_weight": "63.54u",
//         "electronic_configuration": "K2-L8-M18-N1-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "30",
//         "element_name": "Zinc",
//         "element_symbol": "Zn",
//         "electrons": "30",
//         "protons": "30",
//         "neutrons": "35",
//         "atomic_weight": "65.38u",
//         "electronic_configuration": "K2-L8-M18-N2-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "31",
//         "element_name": "Gallium",
//         "element_symbol": "Ga",
//         "electrons": "31",
//         "protons": "31",
//         "neutrons": "39",
//         "atomic_weight": "69.72u",
//         "electronic_configuration": "K2-L8-M18-N3-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "32",
//         "element_name": "Germanium",
//         "element_symbol": "Ge",
//         "electrons": "32",
//         "protons": "32",
//         "neutrons": "41",
//         "atomic_weight": "72.64u",
//         "electronic_configuration": "K2-L8-M18-N4-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "33",
//         "element_name": "Arsenic",
//         "element_symbol": "As",
//         "electrons": "33",
//         "protons": "33",
//         "neutrons": "42",
//         "atomic_weight": "74.92u",
//         "electronic_configuration": "K2-L8-M18-N5-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "34",
//         "element_name": "Selenium",
//         "element_symbol": "Se",
//         "electrons": "34",
//         "protons": "34",
//         "neutrons": "45",
//         "atomic_weight": "78.96u",
//         "electronic_configuration": "K2-L8-M18-N6-O0-P0-Q0-R0"
//     },
//     {
//         "atomic_number": "35",
//         "element_name": "Bromine",
//         "element_symbol": "Br",
//         "electrons": "35",
//         "protons": "35",
//         "neutrons": "45",
//         "atomic_weight": "79.90u",
//         "electronic_configuration": "K2-L8-M18-N7-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "36",
//         "element_name": "Krypton",
//         "element_symbol": "Kr",
//         "electrons": "36",
//         "protons": "36",
//         "neutrons": "48",
//         "atomic_weight": "83.79u",
//         "electronic_configuration": "K2-L8-M18-N8-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "37",
//         "element_name": "Rubidium",
//         "element_symbol": "Rb",
//         "electrons": "37",
//         "protons": "37",
//         "neutrons": "48",
//         "atomic_weight": "85.46u",
//         "electronic_configuration": "K2-L8-M18-N8-O1-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "38",
//         "element_name": "Strontium",
//         "element_symbol": "",
//         "electrons": "38",
//         "protons": "38",
//         "neutrons": "50",
//         "atomic_weight": "87.62u",
//         "electronic_configuration": "K2-L8-M18-N8-O2-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "39",
//         "element_name": "Yttrium",
//         "element_symbol": "Y",
//         "electrons": "39",
//         "protons": "39",
//         "neutrons": "50",
//         "atomic_weight": "88.90u",
//         "electronic_configuration": "K2-L8-M18-N9-O2-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "40",
//         "element_name": "Zirconium",
//         "element_symbol": "Zr",
//         "electrons": "40",
//         "protons": "40",
//         "neutrons": "51",
//         "atomic_weight": "91.22u",
//         "electronic_configuration": "K2-L8-M18-N10-O2-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "41",
//         "element_name": "Niobium",
//         "element_symbol": "Nb",
//         "electrons": "41",
//         "protons": "41",
//         "neutrons": "52",
//         "atomic_weight": "92.90u",
//         "electronic_configuration": "K2-L8-M18-N12-O1-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "42",
//         "element_name": "Molybdenum",
//         "element_symbol": "Mo",
//         "electrons": "42",
//         "protons": "42",
//         "neutrons": "54",
//         "atomic_weight": "95.94u",
//         "electronic_configuration": "K2-L8-M18-N13-O1-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "43",
//         "element_name": "Technetium",
//         "element_symbol": "Tc",
//         "electrons": "43",
//         "protons": "43",
//         "neutrons": "55",
//         "atomic_weight": "98.90u",
//         "electronic_configuration": "K2-L8-M18-N13-O2-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "44",
//         "element_name": "Ruthenium",
//         "element_symbol": "Ru",
//         "electrons": "44",
//         "protons": "44",
//         "neutrons": "57",
//         "atomic_weight": "101.07u",
//         "electronic_configuration": "K2-L8-M18-N15-O1-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "45",
//         "element_name": "Rhodium",
//         "element_symbol": "Rh",
//         "electrons": "45",
//         "protons": "45",
//         "neutrons": "57",
//         "atomic_weight": "102.905u",
//         "electronic_configuration": "K2-L8-M18-N16-O1-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "46",
//         "element_name": "Palladium",
//         "element_symbol": "Pd",
//         "electrons": "46",
//         "protons": "46",
//         "neutrons": "60",
//         "atomic_weight": "106.42u",
//         "electronic_configuration": "K2-L8-M18-N18-O0-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "47",
//         "element_name": "Silver",
//         "element_symbol": "Ag",
//         "electrons": "47",
//         "protons": "47",
//         "neutrons": "61",
//         "atomic_weight": "107.86u",
//         "electronic_configuration": "K2-L8-M18-N18-O1-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "48",
//         "element_name": "Cadmium",
//         "element_symbol": "Cd",
//         "electrons": "48",
//         "protons": "48",
//         "neutrons": "64",
//         "atomic_weight": "112.41u",
//         "electronic_configuration": "K2-L8-M18-N18-O2-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "49",
//         "element_name": "Indium",
//         "element_symbol": "In",
//         "electrons": "49",
//         "protons": "49",
//         "neutrons": "64",
//         "atomic_weight": "114.81u",
//         "electronic_configuration": "K2-L8-M18-N18-O3-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "50",
//         "element_name": "Tin",
//         "element_symbol": "Sn",
//         "electrons": "50",
//         "protons": "50",
//         "neutrons": "69",
//         "atomic_weight": "118.71u",
//         "electronic_configuration": "K2-L8-M18-N18-O4-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "51",
//         "element_name": "Antimony",
//         "element_symbol": "Sb",
//         "electrons": "51",
//         "protons": "51",
//         "neutrons": "71",
//         "atomic_weight": "121.76u",
//         "electronic_configuration": "K2-L8-M18-N18-O5-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "52",
//         "element_name": "Tellurium",
//         "element_symbol": "Te",
//         "electrons": "52",
//         "protons": "52",
//         "neutrons": "75",
//         "atomic_weight": "127.60u",
//         "electronic_configuration": "K2-L8-M18-N18-O6-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "53",
//         "element_name": "Iodine",
//         "element_symbol": "I",
//         "electrons": "53",
//         "protons": "53",
//         "neutrons": "74",
//         "atomic_weight": "126.90u",
//         "electronic_configuration": "K2-L8-M18-N18-O7-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "54",
//         "element_name": "Xenon",
//         "element_symbol": "Xe",
//         "electrons": "54",
//         "protons": "54",
//         "neutrons": "77",
//         "atomic_weight": "131.29u",
//         "electronic_configuration": "K2-L8-M18-N18-O8-P0-Q0-R0",
//     },
//     {
//         "atomic_number": "55",
//         "element_name": "Cesium",
//         "element_symbol": "Cs",
//         "electrons": "55",
//         "protons": "55",
//         "neutrons": "78",
//         "atomic_weight": "132.90u",
//         "electronic_configuration": "K2-L8-M18-N18-O8-P1-Q0-R0",
//     },
//     {
//         "atomic_number": "56",
//         "element_name": "Barium",
//         "element_symbol": "Ba",
//         "electrons": "56",
//         "protons": "56",
//         "neutrons": "81",
//         "atomic_weight": "137.32u",
//         "electronic_configuration": "K2-L8-M18-N18-O8-P2-Q0-R0",
//     },
//     {
//         "atomic_number": "57",
//         "element_name": "Lanthanum",
//         "element_symbol": "Ln",
//         "electrons": "57",
//         "protons": "57",
//         "neutrons": "82",
//         "atomic_weight": "138.90u",
//         "electronic_configuration": "K2-L8-M18-N18-O9-P2-Q0-R0",
//         "family": "'l'"
//     },
//     {
//         "atomic_number": "58",
//         "element_name": "Cerium",
//         "element_symbol": "Ce",
//         "electrons": "58",
//         "protons": "58",
//         "neutrons": "82",
//         "atomic_weight": "140.11u",
//         "electronic_configuration": "K2-L8-M18-N19-O9-P2-Q0-R0",
//         "family": "'l'"
//     },
//     {
//         "atomic_number": "59",
//         "element_name": "Praseodymium",
//         "element_symbol": "Pr",
//         "electrons": "59",
//         "protons": "59",
//         "neutrons": "59",
//         "atomic_weight": "140.90u",
//         "electronic_configuration": "K2-L8-M18-N21-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "60",
//         "element_name": "Neodymium",
//         "element_symbol": "Nd",
//         "electrons": "60",
//         "protons": "60",
//         "neutrons": "60",
//         "atomic_weight": "144.24u",
//         "electronic_configuration": "K2-L8-M18-N18-O22-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "61",
//         "element_name": "Promethium",
//         "element_symbol": "Pm",
//         "electrons": "61",
//         "protons": "61",
//         "neutrons": "61",
//         "atomic_weight": "145.00u",
//         "electronic_configuration": "K2-L8-M18-N23-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "62",
//         "element_name": "Samarium",
//         "element_symbol": "Sm",
//         "electrons": "62",
//         "protons": "62",
//         "neutrons": "62",
//         "atomic_weight": "150.36u",
//         "electronic_configuration": "K2-L8-M18-N24-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "63",
//         "element_name": "Europium",
//         "element_symbol": "Eu",
//         "electrons": "63",
//         "protons": "63",
//         "neutrons": "63",
//         "atomic_weight": "151.96u",
//         "electronic_configuration": "K2-L8-M18-N24-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "64",
//         "element_name": "Gadolinium",
//         "element_symbol": "Gd",
//         "electrons": "64",
//         "protons": "64",
//         "neutrons": "64",
//         "atomic_weight": "157.25u",
//         "electronic_configuration": "K2-L8-M18-N25-O9-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "65",
//         "element_name": "Terbium",
//         "element_symbol": "Tb",
//         "electrons": "65",
//         "protons": "65",
//         "neutrons": "65",
//         "atomic_weight": "158.92u",
//         "electronic_configuration": "K2-L8-M18-N27-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "66",
//         "element_name": "Dysprosium",
//         "element_symbol": "Dy",
//         "electrons": "66",
//         "protons": "66",
//         "neutrons": "66",
//         "atomic_weight": "162.50u",
//         "electronic_configuration": "K2-L8-M18-N28-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "67",
//         "element_name": "Holmium",
//         "element_symbol": "Ho",
//         "electrons": "67",
//         "protons": "67",
//         "neutrons": "67",
//         "atomic_weight": "164.93u",
//         "electronic_configuration": "K2-L8-M18-N29-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "68",
//         "element_name": "Erbium",
//         "element_symbol": "Er",
//         "electrons": "68",
//         "protons": "68",
//         "neutrons": "68",
//         "atomic_weight": "167.25u",
//         "electronic_configuration": "K2-L8-M18-N30-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "69",
//         "element_name": "Thulium",
//         "element_symbol": "",
//         "electrons": "69",
//         "protons": "69",
//         "neutrons": "69",
//         "atomic_weight": "168.93u",
//         "electronic_configuration": "K2-L8-M18-N31-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "70",
//         "element_name": "Ytterbium",
//         "element_symbol": "Yb",
//         "electrons": "70",
//         "protons": "70",
//         "neutrons": "70",
//         "atomic_weight": "172.04u",
//         "electronic_configuration": "K2-L8-M18-N32-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "71",
//         "element_name": "Lutetium",
//         "element_symbol": "Lu",
//         "electrons": "71",
//         "protons": "71",
//         "neutrons": "71",
//         "atomic_weight": "174.96u",
//         "electronic_configuration": "K2-L8-M18-N32-O9-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "72",
//         "element_name": "Hafnium",
//         "element_symbol": "Hf",
//         "electrons": "72",
//         "protons": "72",
//         "neutrons": "72",
//         "atomic_weight": "178.59u",
//         "electronic_configuration": "K2-L8-M18-N31-O8-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "73",
//         "element_name": "Tantalum",
//         "element_symbol": "Ta",
//         "electrons": "73",
//         "protons": "73",
//         "neutrons": "73",
//         "atomic_weight": "180.94u",
//         "electronic_configuration": "K2-L8-M18-N32-O11-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "74",
//         "element_name": "Tungsten",
//         "element_symbol": "W",
//         "electrons": "74",
//         "protons": "74",
//         "neutrons": "74",
//         "atomic_weight": "183.84u",
//         "electronic_configuration": "K2-L8-M18-N32-O12-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "75",
//         "element_name": "Rhenium",
//         "element_symbol": "Re",
//         "electrons": "75",
//         "protons": "75",
//         "neutrons": "75",
//         "atomic_weight": "186.20u",
//         "electronic_configuration": "K2-L8-M18-N32-O13-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "76",
//         "element_name": "Osmium",
//         "element_symbol": "Os",
//         "electrons": "76",
//         "protons": "76",
//         "neutrons": "76",
//         "atomic_weight": "190.23u",
//         "electronic_configuration": "K2-L8-M18-N32-O14-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "77",
//         "element_name": "Iridium",
//         "element_symbol": "Ir",
//         "electrons": "77",
//         "protons": "77",
//         "neutrons": "77",
//         "atomic_weight": "192.21u",
//         "electronic_configuration": "K2-L8-M18-N32-O15-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "78",
//         "element_name": "Platinum",
//         "element_symbol": "Pt",
//         "electrons": "78",
//         "protons": "78",
//         "neutrons": "78",
//         "atomic_weight": "195.07u",
//         "electronic_configuration": "K2-L8-M18-N32-O17-P1-Q0-R0"
//     },
//     {
//         "atomic_number": "79",
//         "element_name": "Gold",
//         "element_symbol": "Au",
//         "electrons": "79",
//         "protons": "79",
//         "neutrons": "79",
//         "atomic_weight": "196.96u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P1-Q0-R0"
//     },
//     {
//         "atomic_number": "80",
//         "element_name": "Mercury",
//         "element_symbol": "Hg",
//         "electrons": "80",
//         "protons": "80",
//         "neutrons": "80",
//         "atomic_weight": "200.59u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "81",
//         "element_name": "Thglium",
//         "element_symbol": "Tl",
//         "electrons": "81",
//         "protons": "81",
//         "neutrons": "81",
//         "atomic_weight": "204.83u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P3-Q0-R0"
//     },
//     {
//         "atomic_number": "82",
//         "element_name": "Lead",
//         "element_symbol": "Pb",
//         "electrons": "82",
//         "protons": "82",
//         "neutrons": "82",
//         "atomic_weight": "207.20u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P4-Q0-R0"
//     },
//     {
//         "atomic_number": "83",
//         "element_name": "Bismuth",
//         "element_symbol": "Bi",
//         "electrons": "83",
//         "protons": "83",
//         "neutrons": "83",
//         "atomic_weight": "208.98u",
//         "electronic_configuration": "K2-L8-M18-N32-O1-P2-Q0-R0"
//     },
//     {
//         "atomic_number": "84",
//         "element_name": "Polonium",
//         "element_symbol": "Po",
//         "electrons": "84",
//         "protons": "84",
//         "neutrons": "84",
//         "atomic_weight": "209.00u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P6-Q0-R0"
//     },
//     {
//         "atomic_number": "85",
//         "element_name": "Astatine",
//         "element_symbol": "As",
//         "electrons": "85",
//         "protons": "85",
//         "neutrons": "85",
//         "atomic_weight": "210.00u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P7-Q0-R0"
//     },
//     {
//         "atomic_number": "86",
//         "element_name": "Radon",
//         "element_symbol": "Rn",
//         "electrons": "86",
//         "protons": "86",
//         "neutrons": "86",
//         "atomic_weight": "222u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P8-Q0-R0"
//     },
//     {
//         "atomic_number": "87",
//         "element_name": "Francium",
//         "element_symbol": "Fr",
//         "electrons": "87",
//         "protons": "87",
//         "neutrons": "87",
//         "atomic_weight": "223u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P8-Q1-R0"
//     },
//     {
//         "atomic_number": "88",
//         "element_name": "Radium",
//         "element_symbol": "Ra",
//         "electrons": "88",
//         "protons": "88",
//         "neutrons": "88",
//         "atomic_weight": "226u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "89",
//         "element_name": "Actinium",
//         "element_symbol": "Ac",
//         "electrons": "89",
//         "protons": "89",
//         "neutrons": "89",
//         "atomic_weight": "227u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P9-Q2-R0"
//     },
//     {
//         "atomic_number": "90",
//         "element_name": "Thorium",
//         "element_symbol": "Th",
//         "electrons": "90",
//         "protons": "90",
//         "neutrons": "90",
//         "atomic_weight": "232.03u",
//         "electronic_configuration": "K2-L8-M18-N32-O18-P10-Q2-R0"
//     },
//     {
//         "atomic_number": "91",
//         "element_name": "Protactinium",
//         "element_symbol": "Pa",
//         "electrons": "91",
//         "protons": "91",
//         "neutrons": "91",
//         "atomic_weight": "231.03u",
//         "electronic_configuration": "K2-L8-M18-N32-O20-P9-Q2-R0"
//     },
//     {
//         "atomic_number": "92",
//         "element_name": "Uranium",
//         "element_symbol": "U",
//         "electrons": "92",
//         "protons": "92",
//         "neutrons": "92",
//         "atomic_weight": "238.02u",
//         "electronic_configuration": "K2-L8-M18-N32-O21-P9-Q2-R0"
//     },
//     {
//         "atomic_number": "93",
//         "element_name": "Neptunium",
//         "element_symbol": "Np",
//         "electrons": "93",
//         "protons": "93",
//         "neutrons": "93",
//         "atomic_weight": "237u",
//         "electronic_configuration": "K2-L8-M18-N32-O22-P9-Q2-R0"
//     },
//     {
//         "atomic_number": "94",
//         "element_name": "Plutonium",
//         "element_symbol": "Pu",
//         "electrons": "94",
//         "protons": "94",
//         "neutrons": "94",
//         "atomic_weight": "244u",
//         "electronic_configuration": "K2-L8-M18-N32-O24-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "95",
//         "element_name": "Americium",
//         "element_symbol": "Am",
//         "electrons": "95",
//         "protons": "95",
//         "neutrons": "95",
//         "atomic_weight": "243u",
//         "electronic_configuration": "K2-L8-M18-N32-O25-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "96",
//         "element_name": "Curium",
//         "element_symbol": "Cm",
//         "electrons": "96",
//         "protons": "96",
//         "neutrons": "96",
//         "atomic_weight": "247u",
//         "electronic_configuration": "K2-L8-M18-N32-O25-P9-Q2-R0"
//     },
//     {
//         "atomic_number": "97",
//         "element_name": "Berkelium",
//         "element_symbol": "Bk",
//         "electrons": "97",
//         "protons": "97",
//         "neutrons": "97",
//         "atomic_weight": "247u",
//         "electronic_configuration": "K2-L8-M18-N32-O27-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "98",
//         "element_name": "Californium",
//         "element_symbol": "Cf",
//         "electrons": "98",
//         "protons": "98",
//         "neutrons": "98",
//         "atomic_weight": "251u",
//         "electronic_configuration": "K2-L8-M18-N32-O28-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "99",
//         "element_name": "Einsteinium",
//         "element_symbol": "Es",
//         "electrons": "99",
//         "protons": "99",
//         "neutrons": "99",
//         "atomic_weight": "252u",
//         "electronic_configuration": "K2-L8-M18-N32-O29-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "100",
//         "element_name": "Fermium",
//         "element_symbol": "Fe",
//         "electrons": "100",
//         "protons": "100",
//         "neutrons": "100",
//         "atomic_weight": "257u",
//         "electronic_configuration": "K2-L8-M18-N32-O30-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "101",
//         "element_name": "Mendelevium",
//         "element_symbol": "Md",
//         "electrons": "101",
//         "protons": "101",
//         "neutrons": "101",
//         "atomic_weight": "258u",
//         "electronic_configuration": "K2-L8-M18-N32-O31-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "102",
//         "element_name": "Nobelium",
//         "element_symbol": "No",
//         "electrons": "102",
//         "protons": "102",
//         "neutrons": "102",
//         "atomic_weight": "259u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P8-Q2-R0"
//     },
//     {
//         "atomic_number": "103",
//         "element_name": "Lawrencium",
//         "element_symbol": "Lr",
//         "electrons": "103",
//         "protons": "103",
//         "neutrons": "103",
//         "atomic_weight": "262u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P8-Q3-R0"
//     },
//     {
//         "atomic_number": "104",
//         "element_name": "Rutherfordium",
//         "element_symbol": "Rf",
//         "electrons": "104",
//         "protons": "104",
//         "neutrons": "104",
//         "atomic_weight": "261",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P10-Q2-R0"
//     },
//     {
//         "atomic_number": "105",
//         "element_name": "Dubnium",
//         "element_symbol": "Db",
//         "electrons": "105",
//         "protons": "105",
//         "neutrons": "105",
//         "atomic_weight": "262u",
//         "electronic_configuration": "K2-L8-M18-N32-O31-P11-Q2-R0"
//     },
//     {
//         "atomic_number": "106",
//         "element_name": "Seaborgium",
//         "element_symbol": "Sg",
//         "electrons": "106",
//         "protons": "106",
//         "neutrons": "106",
//         "atomic_weight": "266u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P12-Q2-R0"
//     },
//     {
//         "atomic_number": "107",
//         "element_name": "Bohrium",
//         "element_symbol": "Bh",
//         "electrons": "107",
//         "protons": "107",
//         "neutrons": "107",
//         "atomic_weight": "264u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P13-Q2-R0"
//     },
//     {
//         "atomic_number": "108",
//         "element_name": "Hassium",
//         "element_symbol": "Hs",
//         "electrons": "108",
//         "protons": "108",
//         "neutrons": "108",
//         "atomic_weight": "277u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P14-Q2-R0"
//     },
//     {
//         "atomic_number": "109",
//         "element_name": "Meitnerium",
//         "element_symbol": "Mt",
//         "electrons": "109",
//         "protons": "109",
//         "neutrons": "109",
//         "atomic_weight": "268u",
//         "electronic_configuration": "K2-L8-M18-N32-O15-P2-Q-R0"
//     },
//     {
//         "atomic_number": "110",
//         "element_name": "Darmstadtium",
//         "element_symbol": "Ds",
//         "electrons": "110",
//         "protons": "110",
//         "neutrons": "110",
//         "atomic_weight": "281u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P16-Q2-R0"
//     },
//     {
//         "atomic_number": "111",
//         "element_name": "Roentgenium",
//         "element_symbol": "Rg",
//         "electrons": "111",
//         "protons": "111",
//         "neutrons": "111",
//         "atomic_weight": "272u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P17-Q2-R0"
//     },
//     {
//         "atomic_number": "112",
//         "element_name": "Copernicium",
//         "element_symbol": "Cn",
//         "electrons": "112",
//         "protons": "112",
//         "neutrons": "112",
//         "atomic_weight": "285u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q2-R0"
//     },
//     {
//         "atomic_number": "113",
//         "element_name": "Nihonium",
//         "element_symbol": "Nh",
//         "electrons": "113",
//         "protons": "113",
//         "neutrons": "113",
//         "atomic_weight": "284u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q3-R0"
//     },
//     {
//         "atomic_number": "114",
//         "element_name": "Fleovium",
//         "element_symbol": "Fl",
//         "electrons": "114",
//         "protons": "114",
//         "neutrons": "114",
//         "atomic_weight": "289u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q4-R0"
//     },
//     {
//         "atomic_number": "115",
//         "element_name": "Moscovium",
//         "element_symbol": "Mc",
//         "electrons": "115",
//         "protons": "115",
//         "neutrons": "115",
//         "atomic_weight": "288u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q5-R0"
//     },
//     {
//         "atomic_number": "116",
//         "element_name": "Livermorium",
//         "element_symbol": "Lv",
//         "electrons": "116",
//         "protons": "116",
//         "neutrons": "116",
//         "atomic_weight": "292u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q6-R0"
//     },
//     {
//         "atomic_number": "117",
//         "element_name": "Tennessine",
//         "element_symbol": "Ts",
//         "electrons": "117",
//         "protons": "117",
//         "neutrons": "117",
//         "atomic_weight": "294u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q7-R0"
//     },
//     {
//         "atomic_number": "118",
//         "element_name": "Oganesson",
//         "element_symbol": "Og",
//         "electrons": "118",
//         "protons": "118",
//         "neutrons": "118",
//         "atomic_weight": "294u",
//         "electronic_configuration": "K2-L8-M18-N32-O32-P18-Q8-R0"
//     },
// ]

// function darkMode() {
//     if (flag === "true") {
//         document.body.style.background = "white";
//         flag_h1 = true;
//         if (flag_h1 === "true") {
//             document.getElementById('color').style.color = '#000000';
//         }
//         flag = "false";
//     } else {
//         document.body.style.background = "black";
//         flag = "true";
//     }
// }